#!/bin/bash

npm set init.author.name $NPM_NAME
npm set init.author.email $NPM_EMAIL
npm set init.author.url $NPM_URL
npm adduser <<!
$NPM_USERNAME
$NPM_PASSWORD
$NPM_EMAIL
!
npm publish ./ --tag $WERCKER_GIT_COMMIT
